# Generated by Django 3.2.16 on 2022-10-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
