# Generated by Django 3.2.16 on 2022-10-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_auto_20221025_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phoneno', models.CharField(max_length=10)),
                ('desc', models.TextField()),
            ],
        ),
    ]
