# Generated by Django 3.2.16 on 2022-10-31 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('items', models.CharField(max_length=1500)),
                ('address', models.TextField()),
                ('quantity', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('phoneno', models.CharField(max_length=10)),
                ('delivery', models.BooleanField(default=False)),
            ],
        ),
    ]
