# Generated by Django 3.2.16 on 2022-10-31 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
